batch_size: 32
lr: 0.0004
epochs: 100
log_interval: 100
save_model: true
dry_run: false

timesteps: 1000
schedule: 'linear'

sr: 16000
n_fft: 1024
hop_length: 256
win_length: 1024
n_mels: 80
power: 1
f_min: 0.0
f_max: 8000.0
norm: "slaney"
mel_scale: "slaney"
spectrogram_time_dim: 160
channels: 1

n_spectrogram: 1
